[window]
dimensions.columns = 100
dimensions.lines = 30
opacity= 0.85
decorations= "None"
[window.padding]
x = 5
y =5

[font]
normal.family = "JetBrainsMono Nerd Font"

[general]

import = ["~/.config/alacritty/rose-pine.toml"]
